// Generated by tools/gen_fixtures.py. Do not edit by hand.
#pragma once

namespace dwarf {
namespace fixtures {

struct Fixture {
    const char* name;
    const char* json;
};

inline constexpr Fixture kCommands[] = {
    {"hb", "{\"c\":\"hb\"}"},
    {"arm_on", "{\"c\":\"arm\",\"v\":true}"},
    {"arm_off", "{\"c\":\"arm\",\"v\":false}"},
    {"aim", "{\"c\":\"aim\",\"pan\":12.5,\"tilt\":-3.0}"},
    {"park", "{\"c\":\"park\"}"},
    {"shoot", "{\"c\":\"shoot\",\"pan\":14.0,\"tilt\":-2.5,\"ms\":300}"},
    {"charge_off", "{\"c\":\"charge\",\"v\":false}"},
    {"fan_on", "{\"c\":\"fan\",\"v\":true}"},
    {"cfg", "{\"c\":\"cfg\",\"panMin\":-60,\"panMax\":60,\"tiltMin\":-30,\"tiltMax\":40}"}
};
inline constexpr int kCommandsCount = 9;

inline constexpr Fixture kStatus[] = {
    {"idle", "{\"armed\":false,\"pan\":0,\"tilt\":0,\"tank\":\"ok\",\"pump\":false,\"charge\":true,\"fan\":false,\"temp\":21.5,\"fault\":null,\"shots\":0}"},
    {"armed_shooting", "{\"armed\":true,\"pan\":12.5,\"tilt\":-3,\"tank\":\"ok\",\"pump\":true,\"charge\":false,\"fan\":false,\"temp\":31.3,\"fault\":null,\"shots\":12}"},
    {"tank_empty", "{\"armed\":false,\"pan\":0,\"tilt\":0,\"tank\":\"low\",\"pump\":false,\"charge\":true,\"fan\":false,\"temp\":24,\"fault\":\"TANK_EMPTY\",\"shots\":3}"},
    {"overtemp", "{\"armed\":false,\"pan\":0,\"tilt\":0,\"tank\":\"ok\",\"pump\":false,\"charge\":true,\"fan\":true,\"temp\":63.4,\"fault\":\"OVERTEMP\",\"shots\":8}"},
    {"ack_reject", "{\"ack\":\"shoot\",\"ok\":false,\"why\":\"cooldown\"}"},
    {"ack_ok", "{\"ack\":\"arm\",\"ok\":true}"}
};
inline constexpr int kStatusCount = 6;

}  // namespace fixtures
}  // namespace dwarf
