#!/usr/bin/env python3
"""Generate a C++ header of canonical protocol messages from protocol/fixtures/.

Run from the repository root:
    python3 tools/gen_fixtures.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "protocol" / "fixtures"
OUT = ROOT / "firmware" / "lib" / "dwarf" / "test_fixtures.h"


def cpp_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def emit_group(name: str, mapping: dict) -> str:
    rows = ",\n".join(
        f'    {{"{key}", "{cpp_escape(value)}"}}' for key, value in mapping.items()
    )
    return (
        f"inline constexpr Fixture k{name}[] = {{\n{rows}\n}};\n"
        f"inline constexpr int k{name}Count = {len(mapping)};\n"
    )


def main() -> None:
    commands = json.loads((FIXTURES / "commands.json").read_text())
    status = json.loads((FIXTURES / "status.json").read_text())

    body = [
        "// Generated by tools/gen_fixtures.py. Do not edit by hand.",
        "#pragma once",
        "",
        "namespace dwarf {",
        "namespace fixtures {",
        "",
        "struct Fixture {",
        "    const char* name;",
        "    const char* json;",
        "};",
        "",
        emit_group("Commands", commands),
        emit_group("Status", status),
        "}  // namespace fixtures",
        "}  // namespace dwarf",
        "",
    ]
    OUT.write_text("\n".join(body))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(commands)} commands, {len(status)} status")


if __name__ == "__main__":
    main()
